//! [`generate`]: a specification and its scene to every document of the project (packet G3b,
//! design note section 4.2) — the Task IR ([`compile_task`]), the teacher's and the student's
//! Observation, Learning, Deployment and Evaluation IRs, the training recipes and the cycle.
//!
//! A function of its inputs: no clock, ordered collections only, the same bytes every run. The
//! constructions are those of the hand-built generators they replace
//! (`crates/es/tests/{shadow_hand,views}.rs`), which are its regression oracle: the Shadow Hand
//! and SO-101 views specs regenerate those committed documents hash for hash
//! (`crates/es-script/tests/estask_generate.rs`).

use std::path::Path;

use es_assets::scene::SceneDesc;
use es_core::TickRate;
use es_ir::deployment::{
    ActionContract, ActionSpace, Deadlines, DeploymentIr, ExecutionMode, FallbackPolicy, Limit,
    Micros, RateLimit, RateSpec, RobotRef, RobotTarget, SafetyEnvelope, Watchdog, WatchdogSet,
    Workspace,
};
use es_ir::evaluation::{
    AcceptanceCriterion, Aggregation, AugmentationPolicy, Comparator, Distribution as Dist,
    EpisodeBatch, EvaluationIr, MetricSpec, Perturbation, PerturbationKind, PerturbationSuite,
    Range, ReplayPolicy, SeedPlan,
};
use es_ir::graph::{NodeId, PortRef};
use es_ir::image::{ImageDType, ImageSpec, Intrinsics};
use es_ir::observation::{
    AugmentKind, CropMode, Io, NormalizeStats, ObservationIr, ObservationNode, ObservationOutput,
    TemporalWindow,
};
use es_ir::task::{ObsSource, TaskIr};
use es_ir::types::{Align, ElemType, Frame, PortType, Shape, Unit};

use super::compile::load_scene;
use super::project::{Preset, Student};
use super::{compile_task, learning, recipes, refuse, Relation, SpecError, TaskSpec};

/// One file of the project: its name in the output directory and its text.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Document {
    pub file: String,
    pub text: String,
}

/// Every document `spec` describes, against its scene `root.join(spec.scene)`. `out` is the
/// directory the documents will be written to as the recipes should name it (relative to the
/// project root, e.g. `tests/fixtures/shadow-hand`); `source` is what each header names as the
/// specification it was generated from.
///
/// Writes `task.toml`; with `[teacher]` its `observation-`, `learning-`, `deployment-`,
/// `evaluation-` and `training-teacher.toml`; with `[student]` (arm `<name>`, default
/// `student`) the same five plus `evaluation-<name>-nominal.toml`; with `[student]` and
/// `[cycle]`, `cycle-<name>.toml`. Every document is validated and every arm passes the
/// cross-IR check before anything is returned.
pub fn generate(
    spec: &TaskSpec,
    root: &Path,
    out: &str,
    source: &str,
) -> Result<Vec<Document>, SpecError> {
    if spec.cycle.is_some() && spec.student.is_none() {
        return refuse("cycle", "student", "a cycle trains the `[student]`");
    }
    let task = compile_task(spec, root)?;
    let (scene, _) = load_scene(&root.join(&spec.scene)).map_err(|reason| SpecError::Scene {
        path: spec.scene.clone(),
        reason,
    })?;
    let robot = super::robot::root_body(spec, root, &scene)?;
    let g = Gen {
        spec,
        scene: &scene,
        task: &task,
        robot: &robot,
    };
    let head = |what: &str| {
        format!(
            "# {what} -- generated by `es project generate` from {source} (scene {}).\n\
             # Change the specification and regenerate; every hash and range here is derived.\n",
            spec.scene
        )
    };
    let mut docs = vec![doc(
        "task.toml",
        &head("Task IR (spec 6)"),
        es_ir::serial::task_to_toml(&task),
    )?];
    let path = |file: &str| join(out, file);
    let init = |arm: &str, bundle: &str| {
        format!(
            "#\n# Its bundle, `{bundle}`, is built from this project's documents:\n#\n\
             #   es policy init --task {} --observation {} \\\n\
             #     --learning {} --deployment {} \\\n#     --out {bundle}\n",
            path("task.toml"),
            path(&format!("observation-{arm}.toml")),
            path(&format!("learning-{arm}.toml")),
            path(&format!("deployment-{arm}.toml")),
        )
    };
    let runs = spec
        .cycle
        .as_ref()
        .and_then(|c| c.runs.clone())
        .unwrap_or_else(|| "runs".to_owned());
    if let Some(teacher) = &spec.teacher {
        let state = match &teacher.state {
            Some(s) => s.clone(),
            None => g.channels(true),
        };
        let obs = g.observation(&[], &state, Preset::H3, true)?;
        let net = learning::teacher(&g, &obs)?;
        let dep = g.deployment(1, 1)?;
        let ev = g.evaluation(&obs, false)?;
        g.cross("teacher", &obs, &net, &dep, &ev)?;
        let recipe = recipes::teacher(teacher, &runs)?;
        let bundle = recipe.policy.bundle.clone().unwrap_or_default();
        docs.extend([
            doc(
                "observation-teacher.toml",
                &head("Observation IR (spec 7), the teacher's"),
                es_ir::serial::observation_to_toml(&obs),
            )?,
            doc(
                "learning-teacher.toml",
                &head("Learning IR (spec 8), the teacher's state MLP"),
                es_ir::serial::learning_to_toml(&net),
            )?,
            doc(
                "deployment-teacher.toml",
                &head("Deployment IR (spec 9), the teacher's"),
                es_ir::serial::deployment_to_toml(&dep),
            )?,
            doc(
                "evaluation-teacher.toml",
                &head("Evaluation IR (spec 10), the teacher's: the nominal suite"),
                es_ir::serial::evaluation_to_toml(&ev),
            )?,
            doc(
                "training-teacher.toml",
                &(head("Training recipe (`es train`), the teacher's PPO")
                    + &init("teacher", &bundle)),
                toml::to_string(&recipe),
            )?,
        ]);
    }
    if let Some(student) = &spec.student {
        let arm = student.name.clone().unwrap_or_else(|| "student".to_owned());
        let (views, state) = g.student_inputs(student)?;
        let preset = student.preset.unwrap_or_default();
        let obs = g.observation(&views, &state, preset, false)?;
        let net = learning::student(&g, student, &obs, &views, &state)?;
        let dep = g.deployment(student.horizon, student.execute)?;
        let ev = g.evaluation(&obs, true)?;
        let nominal = g.evaluation(&obs, false)?;
        g.cross(&arm, &obs, &net, &dep, &ev)?;
        let success_only = spec
            .cycle
            .as_ref()
            .and_then(|c| c.success_only)
            .unwrap_or(false);
        let recipe = recipes::student(student, &arm, &runs, success_only)?;
        let bundle = recipe.policy.bundle.clone().unwrap_or_default();
        let name = |kind: &str| format!("{kind}-{arm}.toml");
        docs.extend([
            doc(
                &name("observation"),
                &head("Observation IR (spec 7), the student's views"),
                es_ir::serial::observation_to_toml(&obs),
            )?,
            doc(
                &name("learning"),
                &head("Learning IR (spec 8), the student"),
                es_ir::serial::learning_to_toml(&net),
            )?,
            doc(
                &name("deployment"),
                &head("Deployment IR (spec 9), the student's"),
                es_ir::serial::deployment_to_toml(&dep),
            )?,
            doc(
                &name("evaluation"),
                &head("Evaluation IR (spec 10), the student's: every suite"),
                es_ir::serial::evaluation_to_toml(&ev),
            )?,
            doc(
                &format!("evaluation-{arm}-nominal.toml"),
                &head("Evaluation IR (spec 10), the student's: the nominal suite"),
                es_ir::serial::evaluation_to_toml(&nominal),
            )?,
            doc(
                &name("training"),
                &(head("Training recipe (`es train`), the student's imitation")
                    + &init(&arm, &bundle)),
                toml::to_string(&recipe),
            )?,
        ]);
        if let Some(c) = &spec.cycle {
            let cycle = recipes::cycle(spec, c, &arm, &bundle, &runs, &path)?;
            let text = head("Cycle (`es loop cycle`)")
                + &format!(
                    "#\n# The demonstrator is {}; the student's bundle is training-{arm}.toml's \
                     (its header).\n",
                    if c.expert.is_some() {
                        "the scripted expert".to_owned()
                    } else {
                        format!(
                            "the trained teacher, `{runs}/teacher.esb` (training-teacher.toml's \
                             chosen checkpoint, `es policy pack`ed)"
                        )
                    }
                );
            docs.push(doc(&name("cycle"), &text, toml::to_string(&cycle))?);
        }
    }
    Ok(docs)
}

/// `dir/file` as a recipe names it: forward slashes, nothing in front of a bare name.
fn join(dir: &str, file: &str) -> String {
    match dir.trim_end_matches(['/', '\\']) {
        "" | "." => file.to_owned(),
        d => format!("{d}/{file}"),
    }
}

fn doc<E: std::fmt::Display>(
    file: &str,
    header: &str,
    body: Result<String, E>,
) -> Result<Document, SpecError> {
    match body {
        Ok(body) => Ok(Document {
            file: file.to_owned(),
            text: format!("{header}\n{body}"),
        }),
        Err(e) => refuse(file, "serialize", e.to_string()),
    }
}

fn hex(d: &[u8; 32]) -> String {
    blake3::Hash::from_bytes(*d).to_hex().to_string()
}

fn checked(at: &str, diags: Vec<es_ir::diag::Diagnostic>) -> Result<(), SpecError> {
    let errors: Vec<_> = diags
        .into_iter()
        .filter(es_ir::diag::Diagnostic::is_error)
        .collect();
    if errors.is_empty() {
        Ok(())
    } else {
        refuse(at, "validate", format!("{errors:?}"))
    }
}

fn f32v(n: u64, unit: Unit, frame: Frame) -> PortType {
    PortType {
        elem: ElemType::F32,
        shape: Shape::new([n]),
        unit,
        frame,
        time: es_ir::types::TimeRef::Tick,
        image: None,
    }
}

/// What every builder reads.
pub(super) struct Gen<'a> {
    pub spec: &'a TaskSpec,
    pub scene: &'a SceneDesc,
    pub task: &'a TaskIr,
    /// The robot's root body.
    pub robot: &'a str,
}

impl Gen<'_> {
    /// `[observe] state`'s channel names, then (with `privileged`) `privileged`'s.
    fn channels(&self, privileged: bool) -> Vec<String> {
        let o = self.spec.observe.clone().unwrap_or_default();
        let mut names: Vec<String> = o.state.unwrap_or_default().into_keys().collect();
        if privileged {
            names.extend(o.privileged.unwrap_or_default().into_keys());
        }
        names
    }

    /// The source a channel was declared with (`robot.joint_pos`, `cube.pose`, ...).
    fn source(&self, channel: &str) -> Option<String> {
        let o = self.spec.observe.as_ref()?;
        [&o.state, &o.privileged]
            .into_iter()
            .flatten()
            .find_map(|m| m.get(channel).cloned())
    }

    pub(super) fn control_hz(&self) -> f64 {
        self.spec.control_hz
    }

    /// Each actuator's `(lo, hi)` ctrlrange, in actuator order.
    pub(super) fn ctrlrange(&self, at: &str) -> Result<Vec<(f64, f64)>, SpecError> {
        self.scene
            .actuators
            .iter()
            .map(|a| match a.ctrl_range {
                Some(r) => Ok(r),
                None => refuse(
                    at,
                    "ctrlrange",
                    format!("actuator `{}` declares none", a.name),
                ),
            })
            .collect()
    }

    /// The student's cameras and state channels, checked against `[observe]`.
    fn student_inputs(&self, s: &Student) -> Result<(Vec<String>, Vec<String>), SpecError> {
        let cameras = self
            .spec
            .observe
            .as_ref()
            .and_then(|o| o.cameras.clone())
            .unwrap_or_default();
        let views = s.views.clone().unwrap_or_else(|| cameras.clone());
        if views.is_empty() {
            return refuse("student", "views", "a student needs a camera");
        }
        for v in &views {
            if !cameras.contains(v) {
                return refuse(
                    "student",
                    "views",
                    format!("`{v}` is not in `[observe] cameras`"),
                );
            }
        }
        let open = self.channels(false);
        let state = s.state.clone().unwrap_or_else(|| open.clone());
        for c in &state {
            if !open.contains(c) {
                return refuse(
                    "student",
                    "state",
                    format!("`{c}` is not an `[observe] state` channel (a student reads no privileged one)"),
                );
            }
        }
        if s.preset == Some(Preset::U3) && state.len() != 1 {
            return refuse(
                "student",
                "state",
                "the `u3` preset fuses exactly one state channel",
            );
        }
        Ok((views, state))
    }

    fn channel(&self, at: &str, name: &str) -> Result<&es_ir::task::ObsChannel, SpecError> {
        match self.task.observation_spec.channels.get(name) {
            Some(c) => Ok(c),
            None => refuse(at, "state", format!("no channel `{name}` in the Task IR")),
        }
    }

    // --- the Observation IR ---------------------------------------------------------------

    /// `views`' image chains and the state of `state`, as `preset` lays it out. `boundary`
    /// lists the state output on the graph's boundary — the teacher's document does, the
    /// camera documents do not (the committed documents' forms; `observation_hash` reads it).
    fn observation(
        &self,
        views: &[String],
        state: &[String],
        preset: Preset,
        boundary: bool,
    ) -> Result<ObservationIr, SpecError> {
        let mut ir = ObservationIr::new(1, self.task.task_hash().map_err(|d| diag("task", &d))?);
        let mut next = 0;
        let mut add = |ir: &mut ObservationIr, node: ObservationNode, from: Option<NodeId>| {
            let id = NodeId(next);
            next += 1;
            ir.graph.insert(id, node);
            if let Some(f) = from {
                ir.graph.connect(f, "out", id, "in0");
            }
            id
        };
        for cam in views {
            let name = format!("rgb_{cam}");
            let ch = self.channel("student.views", &name)?;
            let ObsSource::Sensor { id: sensor, .. } = ch.source else {
                return refuse("student.views", cam, "not a camera channel");
            };
            let raw = ch.ty.clone();
            let spec = raw.image.expect("a camera channel carries its ImageSpec");
            let (width, height) = (spec.width, spec.height);
            // The tensor layout: F32, channels first.
            let chw = |image: ImageSpec, unit: Unit| PortType {
                elem: ElemType::F32,
                shape: Shape::new([3, u64::from(image.height), u64::from(image.width)]),
                unit,
                image: Some(ImageSpec {
                    dtype: ImageDType::F32,
                    ..image
                }),
                ..raw.clone()
            };
            let deq = chw(spec, Unit::Pixel);
            let unit = Unit::Normalized { lo: 0.0, hi: 1.0 };
            let norm = chw(spec, unit.clone());
            // `Pad(4)` moves the principal point with the old origin; the random crop takes the
            // canvas back (DrQ's shift in training, the centre in evaluation: INV-14, INV-15).
            let pad = 4;
            let padded = chw(
                ImageSpec {
                    width: width + 2 * pad,
                    height: height + 2 * pad,
                    intrinsics: Intrinsics {
                        cx: spec.intrinsics.cx + f64::from(pad),
                        cy: spec.intrinsics.cy + f64::from(pad),
                        ..spec.intrinsics
                    },
                    ..spec
                },
                unit,
            );
            let chain = [
                ObservationNode::ImageInput {
                    sensor,
                    io: Io::source(raw.clone()),
                },
                ObservationNode::Dequantize {
                    io: Io::unary(raw, deq.clone()),
                },
                ObservationNode::Normalize {
                    stats: NormalizeStats::Range { lo: 0.0, hi: 1.0 },
                    io: Io::unary(deq, norm.clone()),
                },
                ObservationNode::Pad {
                    left: pad,
                    top: pad,
                    right: pad,
                    bottom: pad,
                    io: Io::unary(norm.clone(), padded.clone()),
                },
                ObservationNode::Crop {
                    mode: CropMode::Random { width, height },
                    rescale_intrinsics: true,
                    io: Io::unary(padded, norm.clone()),
                },
                ObservationNode::Augment {
                    kind: AugmentKind::ColorJitter {
                        brightness: 0.2,
                        contrast: 0.2,
                        saturation: 0.0,
                        hue: 0.0,
                    },
                    training_only: true,
                    io: Io::unary(norm.clone(), norm.clone()),
                },
            ];
            let mut last = None;
            for node in chain {
                last = Some(add(&mut ir, node, last));
            }
            let port = PortRef::new(last.expect("a chain"), "out");
            ir.outputs
                .insert(name, ObservationOutput { port, ty: norm });
        }
        let mut inputs = Vec::new();
        let at = if boundary { "teacher" } else { "student" };
        for name in state {
            let ch = self.channel(at, name)?;
            let source = match ch.source {
                ObsSource::JointState { body, .. } | ObsSource::BodyPose(body) => body,
                ObsSource::PreviousAction { .. } => ObsSource::previous_action_id(),
                _ => return refuse(at, "state", format!("`{name}` is not a state channel")),
            };
            let id = add(
                &mut ir,
                ObservationNode::StateInput {
                    source,
                    io: Io::source(ch.ty.clone()),
                },
                None,
            );
            inputs.push((name, id, ch.ty.clone()));
        }
        if preset == Preset::U3 {
            // Each channel as `[-1, 1]` under its own name.
            for (name, id, ty) in inputs {
                let out = PortType {
                    unit: Unit::Normalized { lo: -1.0, hi: 1.0 },
                    ..ty.clone()
                };
                let n = add(
                    &mut ir,
                    ObservationNode::Normalize {
                        stats: NormalizeStats::Range { lo: -1.0, hi: 1.0 },
                        io: Io::unary(ty, out.clone()),
                    },
                    Some(id),
                );
                ir.outputs.insert(
                    name.clone(),
                    ObservationOutput {
                        port: PortRef::new(n, "out"),
                        ty: out,
                    },
                );
            }
        } else if !inputs.is_empty() {
            let width: u64 = inputs.iter().map(|(_, _, ty)| ty.shape.dims()[0]).sum();
            let wide = f32v(width, Unit::Dimensionless, Frame::World);
            let normalized = PortType {
                unit: Unit::Normalized { lo: -1.0, hi: 1.0 },
                ..wide.clone()
            };
            let parts = inputs.iter().map(|(_, _, ty)| ty.clone()).collect();
            let cat = add(
                &mut ir,
                ObservationNode::Concat {
                    axis: 0,
                    time_align: None,
                    io: Io::new(parts, wide.clone()),
                },
                None,
            );
            for (i, (_, id, _)) in inputs.iter().enumerate() {
                ir.graph.connect(*id, "out", cat, &format!("in{i}"));
            }
            let mut stats = Vec::new();
            for (name, _, _) in &inputs {
                stats.extend(self.stats(name)?);
            }
            let (mean, std) = stats.into_iter().unzip();
            let norm = add(
                &mut ir,
                ObservationNode::Normalize {
                    stats: NormalizeStats::MeanStd { mean, std },
                    io: Io::unary(wide, normalized.clone()),
                },
                Some(cat),
            );
            let port = PortRef::new(norm, "out");
            if boundary {
                ir.graph.outputs.push(port.clone());
            }
            ir.outputs.insert(
                "state".to_owned(),
                ObservationOutput {
                    port,
                    ty: normalized,
                },
            );
        }
        ir.temporal.window = Some(TemporalWindow {
            n_steps: 1,
            stride: 1,
            align: Align::Hold,
        });
        checked("observation", ir.validate())?;
        Ok(ir)
    }

    /// Per-element `(mean, std)` bringing a channel to about `[-1, 1]` from the scene's static
    /// ranges (plan H's `channel_stats`): a joint position by its range, a joint velocity by
    /// 5 rad/s (Isaac Lab's 0.2 scale), the previous action by each ctrlrange, a body's position
    /// by the clause measuring its distance from a point (that point, that radius) or else its
    /// scene position ± 1 m, a quaternion as it is, a velocity 1 m/s and 5 rad/s.
    fn stats(&self, channel: &str) -> Result<Vec<(f64, f64)>, SpecError> {
        let at = format!("state.{channel}");
        let n = |k: usize, m: f64, s: f64| vec![(m, s); k];
        let dim = self.channel(&at, channel)?.ty.shape.dims()[0] as usize;
        let Some(source) = self.source(channel) else {
            return refuse(at, channel, "not an `[observe]` channel");
        };
        Ok(match source.as_str() {
            "robot.joint_pos" => {
                let mut out = Vec::new();
                for j in self.scene.joints.iter().take(dim) {
                    let Some((lo, hi)) = j.range else {
                        return refuse(at, channel, format!("joint `{}` has no range", j.name));
                    };
                    out.push((f64::midpoint(lo, hi), (hi - lo) / 2.0));
                }
                out
            }
            "robot.joint_vel" => n(dim, 0.0, 5.0),
            "robot.previous_action" => self
                .ctrlrange(&at)?
                .into_iter()
                .map(|(lo, hi)| (f64::midpoint(lo, hi), (hi - lo) / 2.0))
                .collect(),
            other => {
                let (body, field) = other.rsplit_once('.').unwrap_or((other, ""));
                match field {
                    "pose" | "qpos" => {
                        let mut p = self.position_stats(body);
                        p.extend(n(4, 0.0, 1.0));
                        p
                    }
                    "vel" => [n(3, 0.0, 1.0), n(3, 0.0, 5.0)].concat(),
                    _ => return refuse(at, channel, format!("no statistics for `{other}`")),
                }
            }
        })
    }

    fn position_stats(&self, body: &str) -> Vec<(f64, f64)> {
        let clauses = self
            .spec
            .failure
            .iter()
            .chain([&self.spec.success])
            .flat_map(|c| &c.clauses);
        for c in clauses {
            let distance = matches!(c.relation, Relation::Near | Relation::FartherThan);
            if let (true, true, Some(p), Some(m)) = (distance, c.subject == body, c.point, c.m) {
                return p.iter().map(|v| (*v, m)).collect();
            }
        }
        let pos = self
            .scene
            .bodies
            .iter()
            .find(|b| b.name == body)
            .map_or(es_math::Vec3::new(0.0, 0.0, 0.0), |b| b.pose.position);
        vec![(pos.x, 1.0), (pos.y, 1.0), (pos.z, 1.0)]
    }

    // --- the Deployment IR ----------------------------------------------------------------

    /// Half the physics rate for a control rate of half of it, and so on: the scene's timestep
    /// in whole nanoseconds (`TickRate::from_period_secs`) divided by the decimation, exactly.
    pub(super) fn control_rate(&self) -> Result<TickRate, SpecError> {
        let at = "the control rate";
        let physics = TickRate::from_period_secs(self.scene.options.timestep).map_err(|e| {
            SpecError::Field {
                at: at.into(),
                field: "timestep".into(),
                reason: e.to_string(),
            }
        })?;
        let hz = self.control_hz();
        let k = (physics.as_hz_f64() / hz).round();
        if !(k >= 1.0 && (physics.as_hz_f64() / k - hz).abs() <= 1e-6 * hz) {
            return refuse(
                at,
                "control_hz",
                format!(
                    "{hz} Hz is not the scene's {} Hz over a whole decimation",
                    physics.as_hz_f64()
                ),
            );
        }
        let k = k as u64;
        let rate = if physics.num() % k == 0 {
            TickRate::rational(physics.num() / k, physics.den())
        } else {
            TickRate::rational(physics.num(), physics.den() * k)
        };
        rate.map_err(|e| SpecError::Field {
            at: at.into(),
            field: "control_hz".into(),
            reason: e.to_string(),
        })
    }

    /// The Safety Plane over every actuator (plan H's `deployment-hand.toml`): the position
    /// envelope is each ctrlrange; the rate stages are twice the widest jump inside it per
    /// control tick (velocity `2 w hz`, acceleration `4 w hz²`, first and second differences
    /// `2 w`, `4 w`), so the position stage is what binds; the torque each forcerange.
    fn deployment(&self, horizon: u32, execute: u32) -> Result<DeploymentIr, SpecError> {
        let range = self.ctrlrange("deploy")?;
        let n = range.len();
        let hz = self.control_hz();
        let width: Vec<f64> = range.iter().map(|(lo, hi)| hi - lo).collect();
        let mut torque = Vec::new();
        for a in &self.scene.actuators {
            let Some((_, hi)) = a.force_range else {
                return refuse(
                    "deploy",
                    "forcerange",
                    format!("actuator `{}` declares none", a.name),
                );
            };
            torque.push(hi);
        }
        let deploy = self.spec.deploy.clone().unwrap_or_default();
        let (min, max) = if let Some(b) = deploy.workspace {
            (b.min, b.max)
        } else {
            let p = self
                .scene
                .bodies
                .iter()
                .find(|b| b.name == self.robot)
                .map_or(es_math::Vec3::new(0.0, 0.0, 0.0), |b| b.pose.position);
            (
                [p.x - 1.0, p.y - 1.0, p.z - 1.0],
                [p.x + 1.0, p.y + 1.0, p.z + 1.0],
            )
        };
        let workspace = Workspace::Box { min, max };
        let control = self.control_rate()?;
        let inference = TickRate::rational(control.num(), control.den() * u64::from(execute))
            .map_err(|e| SpecError::Field {
                at: "student".into(),
                field: "execute".into(),
                reason: e.to_string(),
            })?;
        let dep = DeploymentIr {
            schema_version: 1,
            robot: RobotRef {
                name: deploy.name.unwrap_or_else(|| self.spec.robot.clone()),
                target: RobotTarget::Simulated {
                    scene: self.spec.scene.clone(),
                },
                n_joints: n,
            },
            action: ActionContract {
                space: ActionSpace::JointPosition,
                dim: n,
                horizon: horizon as usize,
                execute_chunk: execute as usize,
            },
            safety: SafetyEnvelope {
                position: range
                    .iter()
                    .map(|(lo, hi)| Limit {
                        lower: *lo,
                        upper: *hi,
                    })
                    .collect(),
                position_soft_margin: vec![0.0; n],
                velocity_max: width.iter().map(|w| 2.0 * w * hz).collect(),
                acceleration_max: width.iter().map(|w| 4.0 * w * hz * hz).collect(),
                torque_max: torque,
                jerk_max: None,
                action_rate: RateLimit {
                    first_diff_max: width.iter().map(|w| 2.0 * w).collect(),
                    second_diff_max: width.iter().map(|w| 4.0 * w).collect(),
                },
                workspace,
                ee_velocity_max: 0.6,
                min_self_distance: 0.005,
                min_env_distance: 0.005,
                contact_force_max: 15.0,
            },
            execution: if horizon == 1 {
                ExecutionMode::RecedingHorizon
            } else {
                ExecutionMode::TemporalEnsemble { decay: 0.01 }
            },
            deadlines: Deadlines {
                observation_age: Micros(240_000),
                inference_budget: Micros(240_000),
                actuation_budget: Micros(10_000),
            },
            watchdogs: WatchdogSet(vec![
                Watchdog::InferenceDeadline {
                    budget: Micros(240_000),
                },
                Watchdog::ChunkUnderrun,
                Watchdog::StaleObservation {
                    max_age: Micros(80_000),
                },
                Watchdog::EnvelopeViolationRate {
                    window: 200,
                    max_frac: 1.0,
                },
            ]),
            fallback: FallbackPolicy::HoldPosition,
            rate: RateSpec { control, inference },
        };
        checked("deployment", dep.validate())?;
        Ok(dep)
    }

    // --- the Evaluation IR ----------------------------------------------------------------

    /// The held-out seeds, the four metrics, success ≥ the threshold on `nominal`; `full` adds
    /// the suites of plan U's `evaluation-augmented.toml`, the observation delay one and two
    /// control periods in whole milliseconds.
    fn evaluation(&self, obs: &ObservationIr, full: bool) -> Result<EvaluationIr, SpecError> {
        let e = self.spec.evaluate.clone().unwrap_or_default();
        let first = e.first_seed.unwrap_or(101);
        let n = e.episodes.unwrap_or(16);
        let mut suites = vec![PerturbationSuite {
            name: "nominal".to_owned(),
            perturbations: Vec::new(),
        }];
        if full {
            let d = (1000.0 / self.control_hz()).round() as u32;
            let kinds = [
                PerturbationKind::LightIntensity {
                    range: Range { lo: 0.5, hi: 1.5 },
                    dist: Dist::Uniform,
                },
                PerturbationKind::LightDirection { range_deg: 45.0 },
                PerturbationKind::ObservationDelay { ms: vec![d, 2 * d] },
                PerturbationKind::TorqueNoise { rel_sigma: 0.05 },
                PerturbationKind::Backlash {
                    rad: Range { lo: 0.0, hi: 0.01 },
                },
            ];
            for (stream, kind) in (0..).zip(kinds) {
                suites.push(PerturbationSuite {
                    name: kind.name().to_owned(),
                    perturbations: vec![Perturbation::new(kind, stream)],
                });
            }
        }
        let ev = EvaluationIr {
            schema_version: 1,
            task: hex(&self.task.task_hash().map_err(|d| diag("task", &d))?),
            observation: hex(&obs
                .observation_hash()
                .map_err(|d| diag("observation", &d))?),
            episodes: EpisodeBatch {
                n_episodes: n,
                seeds: SeedPlan::Explicit((first..first + u64::from(n)).collect()),
            },
            suites,
            metrics: vec![
                MetricSpec::SuccessRate,
                MetricSpec::EpisodeLength,
                MetricSpec::EnvelopeViolationRate,
                MetricSpec::FailureModeHistogram,
            ],
            acceptance: vec![AcceptanceCriterion {
                suite: Some("nominal".to_owned()),
                metric: MetricSpec::SuccessRate,
                comparator: Comparator::Ge,
                threshold: e.success_rate.unwrap_or(0.5),
                aggregation: Aggregation::Mean,
            }],
            augmentation: AugmentationPolicy::Disabled,
            replay: ReplayPolicy::FailuresFirst,
        };
        checked("evaluation", ev.validate())?;
        Ok(ev)
    }

    /// The cross-IR check (spec 5.4) over one arm's five documents.
    fn cross(
        &self,
        arm: &str,
        observation: &ObservationIr,
        learning: &es_ir::learning::LearningGraph,
        deployment: &DeploymentIr,
        evaluation: &EvaluationIr,
    ) -> Result<(), SpecError> {
        checked(
            &format!("the {arm}'s documents"),
            es_ir::cross::check(&es_ir::cross::IrBundle {
                task: self.task,
                observation,
                learning,
                deployment,
                evaluation: Some(evaluation),
            }),
        )
    }
}

fn diag(at: &str, d: &es_ir::diag::Diagnostic) -> SpecError {
    SpecError::Field {
        at: at.to_owned(),
        field: "hash".to_owned(),
        reason: format!("{d:?}"),
    }
}
