[package]
name = "es-physics-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
es-core = { workspace = true }
es-math = { workspace = true }
es-assets = { workspace = true }
es-physics-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
