//! Oracle for `docs/packets/M1/W7-lerobot-dataset.md`.
//!
//! The fixture is synthesised here rather than checked in: a parquet file written by this
//! crate is not evidence about `LeRobot`'s real format (see `docs/api-notes/lerobot-dataset.md`
//! — nothing pins a `lerobot` version yet), so committing one would only look like a golden.
//! What these tests do prove is the round-trip and the spec 19.2 identity properties.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use es_data::{
    Column, DataError, DatasetIdentity, Dtype, Episode, FeatureSpec, Info, LeRobotDataset,
    LeRobotWriter, Split, VideoRef,
};

const LENGTHS: [usize; 3] = [3, 5, 4];
const STATE: usize = 4;

/// A fresh directory under the OS temp dir, removed first so a rerun is clean.
fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("es-data-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

fn features() -> BTreeMap<String, FeatureSpec> {
    let mut f = BTreeMap::new();
    f.insert(
        "action".to_string(),
        FeatureSpec::new(Dtype::Float32, [STATE as u64]),
    );
    f.insert(
        "observation.state".to_string(),
        FeatureSpec::new(Dtype::Float32, [STATE as u64]),
    );
    f.insert(
        "observation.gripper".to_string(),
        FeatureSpec::new(Dtype::Float64, [1]),
    );
    f.insert(
        "observation.images.top".to_string(),
        FeatureSpec::new(Dtype::Video, [2, 2, 3]),
    );
    f
}

fn episode(index: u32, n: usize) -> Episode {
    let seed = f64::from(index) * 100.0;
    let mut columns = BTreeMap::new();
    columns.insert(
        "action".to_string(),
        Column::F32(
            (0..n * STATE)
                .map(|i| (seed + i as f64) as f32 * 0.5)
                .collect(),
        ),
    );
    columns.insert(
        "observation.state".to_string(),
        Column::F32((0..n * STATE).map(|i| -(seed + i as f64) as f32).collect()),
    );
    columns.insert(
        "observation.gripper".to_string(),
        Column::F64((0..n).map(|i| seed + i as f64 / 3.0).collect()),
    );
    Episode {
        index,
        tasks: vec![format!("task {}", index % 2)],
        timestamps: (0..n).map(|i| i as f64 / 30.0).collect(),
        task_index: (0..n).map(|_| i64::from(index % 2)).collect(),
        columns,
        // Regenerated by the reader from `video_path`; see the packet.
        video: BTreeMap::new(),
    }
}

/// Writes the three-episode fixture and returns the dataset root.
fn write_fixture(root: &Path) -> Vec<Episode> {
    let mut writer = LeRobotWriter::create(root, Info::new(30.0, features())).unwrap();
    let episodes: Vec<Episode> = LENGTHS
        .iter()
        .enumerate()
        .map(|(i, n)| episode(i as u32, *n))
        .collect();
    for ep in &episodes {
        writer.write_episode(ep).unwrap();
    }
    writer.finish().unwrap();
    episodes
}

#[test]
fn round_trip_is_lossless_for_non_video_features() {
    let root = scratch("roundtrip");
    let written = write_fixture(&root);

    let ds = LeRobotDataset::open(&root).unwrap();
    assert_eq!(ds.info().total_episodes, 3);
    assert_eq!(ds.info().total_frames, LENGTHS.iter().sum::<usize>() as u64);
    assert_eq!(ds.info().total_tasks, 2);
    assert_eq!(ds.info().total_chunks, 1);
    assert_eq!(ds.episodes().len(), 3);
    assert_eq!(ds.features().len(), 4);

    for (i, want) in written.iter().enumerate() {
        let got = ds.read_episode(i as u32).unwrap();
        assert_eq!(got.timestamps, want.timestamps, "episode {i} timestamps");
        assert_eq!(got.task_index, want.task_index, "episode {i} task_index");
        assert_eq!(got.tasks, want.tasks, "episode {i} tasks");
        assert_eq!(got.columns, want.columns, "episode {i} columns");
        // Video refs are derived, not stored: one per frame, pointing at the episode's mp4.
        let refs = &got.video["observation.images.top"];
        assert_eq!(refs.len(), LENGTHS[i]);
        assert_eq!(
            refs[2],
            VideoRef {
                path: format!("videos/chunk-000/observation.images.top/episode_{i:06}.mp4").into(),
                frame_index: 2,
            }
        );
    }

    // A second write of the same data reads back identically: the writer is a function of
    // its inputs, which is what makes `content_hash` meaningful.
    let again = scratch("roundtrip2");
    write_fixture(&again);
    let ds2 = LeRobotDataset::open(&again).unwrap();
    assert_eq!(ds.read_episode(1).unwrap(), ds2.read_episode(1).unwrap());
}

#[test]
fn port_types_cover_every_feature() {
    let root = scratch("porttypes");
    write_fixture(&root);
    let ds = LeRobotDataset::open(&root).unwrap();
    for (name, feat) in ds.features() {
        let pt = feat.port_type().unwrap();
        assert_eq!(pt.shape.dims(), feat.shape.as_slice(), "{name}");
        assert!(pt.image.is_none(), "{name}: ImageSpec cannot be recovered");
    }
}

#[test]
fn content_hash_tracks_samples_and_schema_hash_does_not() {
    let root = scratch("identity");
    let mut episodes = write_fixture(&root);
    let ds = LeRobotDataset::open(&root).unwrap();
    let split = Split::deterministic(3, [0.34, 0.33, 0.33], 20_260_912);
    let base = DatasetIdentity::compute(&ds, &split).unwrap();

    // One sample value changes -> content differs, schema and split do not.
    let changed = scratch("identity-changed");
    let Column::F32(v) = episodes[1].columns.get_mut("action").unwrap() else {
        unreachable!()
    };
    v[0] += 1.0;
    let mut writer = LeRobotWriter::create(&changed, Info::new(30.0, features())).unwrap();
    for ep in &episodes {
        writer.write_episode(ep).unwrap();
    }
    writer.finish().unwrap();
    let other = DatasetIdentity::compute(&LeRobotDataset::open(&changed).unwrap(), &split).unwrap();
    assert_ne!(base.content, other.content, "content_hash ignored a sample");
    assert_eq!(base.schema, other.schema);
    assert_eq!(base.split, other.split);

    // A schema change -> schema differs.
    let extra = scratch("identity-schema");
    let mut feats = features();
    feats.insert(
        "observation.torque".to_string(),
        FeatureSpec::new(Dtype::Float32, [STATE as u64]),
    );
    let mut writer = LeRobotWriter::create(&extra, Info::new(30.0, feats)).unwrap();
    for ep in &mut episodes {
        ep.columns.insert(
            "observation.torque".to_string(),
            Column::F32(vec![0.0; ep.len() * STATE]),
        );
        writer.write_episode(ep).unwrap();
    }
    writer.finish().unwrap();
    let wider = DatasetIdentity::compute(&LeRobotDataset::open(&extra).unwrap(), &split).unwrap();
    assert_ne!(base.schema, wider.schema, "schema_hash ignored a feature");

    // A different split -> only split differs, and the chain hash follows.
    let other_split = Split {
        train: vec![0, 2],
        val: vec![1],
        test: vec![],
    };
    let resplit = DatasetIdentity::compute(&ds, &other_split).unwrap();
    assert_eq!(base.content, resplit.content);
    assert_eq!(base.schema, resplit.schema);
    assert_ne!(base.split, resplit.split);
    assert_ne!(base.to_dataset_hash(), resplit.to_dataset_hash());
}

#[test]
fn malformed_metadata_is_a_typed_error() {
    let root = scratch("malformed");
    write_fixture(&root);
    std::fs::write(root.join("meta/info.json"), b"{\"fps\": ").unwrap();
    let err = LeRobotDataset::open(&root).unwrap_err();
    assert!(matches!(err, DataError::Json { .. }), "{err}");

    // `fps` present but the wrong type is still a JSON error, not a panic.
    std::fs::write(root.join("meta/info.json"), b"{\"fps\": \"thirty\"}").unwrap();
    assert!(matches!(
        LeRobotDataset::open(&root).unwrap_err(),
        DataError::Json { .. }
    ));

    let missing = scratch("missing");
    let err = LeRobotDataset::open(&missing).unwrap_err();
    assert!(matches!(err, DataError::Io { .. }), "{err}");
}

#[test]
fn episode_length_disagreement_is_reported() {
    let root = scratch("ragged");
    write_fixture(&root);
    let path = root.join("meta/episodes.jsonl");
    let text = std::fs::read_to_string(&path).unwrap();
    std::fs::write(&path, text.replace("\"length\":3", "\"length\":9")).unwrap();
    let ds = LeRobotDataset::open(&root).unwrap();
    let err = ds.read_episode(0).unwrap_err();
    assert!(matches!(err, DataError::Inconsistent(_)), "{err}");
}
