[package]
name = "es-script"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
es-core = { workspace = true }
es-ir = { workspace = true }
es-ir-types = { workspace = true }
es-compile = { workspace = true }
es-eval = { workspace = true }
es-data = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
