//! Oracle for the Observation IR CPU reference plan (spec 11.3, spec 7.7).
//!
//! Two halves: agreement with `tests/golden/observation/**`, which is CI read-only (spec 1.4)
//! and is generated by PyTorch/torchvision (`crates/es-compile/python/gen_observation_goldens.py`,
//! never by the code below), and the properties that hold for every input.
//!
//! Agreement is byte-for-byte except where a golden's sidecar carries a `tolerance_ulp`,
//! which only `srgb_to_linear_lut256` does and only because `DET-010` forbids the `powf` the
//! reference formula uses — see `docs/design/observation-lowering.md` §6.

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;
use std::time::Duration;

use es_compile::{kernels, CpuPlan, Op, PlanMode, Tensor, TensorRef};
use es_core::StableId;
use es_ir::graph::{NodeId, PortRef};
use es_ir::image::{
    CameraModel, ChannelFormat, ColorSpace, DistortionModel, ImageDType, ImageSpec, Intrinsics,
    Rect, ShutterModel,
};
use es_ir::observation::{
    in_port, CropMode, Io, NormalizeStats, ObservationIr, ObservationNode, ObservationOutput,
    ResizeFilter, OUT,
};
use es_ir::types::{Align, ElemType, Frame, PortType, Shape, TimeRef, Unit};
use es_math::conventions::Pose;
use proptest::prelude::*;

const MEAN: [f32; 3] = [0.485, 0.456, 0.406];
const STD: [f32; 3] = [0.229, 0.224, 0.225];

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/observation")
}

fn golden(name: &str) -> Vec<u8> {
    let path = golden_dir().join(format!("{name}.bin"));
    fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "{}: {e}\nregenerate with `ES_PYTHON=<venv>/python python \
             crates/es-compile/python/gen_observation_goldens.py tests/golden/observation`",
            path.display()
        )
    })
}

/// The golden's own declared tolerance, in ULP, or 0 for bit equality. It lives in the
/// sidecar — itself CI read-only — so loosening a comparison means modifying a golden, which
/// `cargo xtask verify-goldens` refuses.
fn tolerance_ulp(name: &str) -> u32 {
    let path = golden_dir().join(format!("{name}.json"));
    let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let sidecar: serde_json::Value = serde_json::from_str(&text).expect("sidecar is JSON");
    sidecar
        .get("tolerance_ulp")
        .and_then(serde_json::Value::as_u64)
        .and_then(|v| u32::try_from(v).ok())
        .unwrap_or(0)
}

fn f32_bytes(v: &[f32]) -> Vec<u8> {
    v.iter().flat_map(|x| x.to_le_bytes()).collect()
}

/// Compare against the oracle's bytes, allowing the sidecar's `tolerance_ulp` and no more.
fn assert_golden(name: &str, got: &[f32]) {
    let want_bytes = golden(name);
    let tol = tolerance_ulp(name);
    if tol == 0 {
        assert_eq!(f32_bytes(got), want_bytes, "{name}");
        return;
    }
    let want: Vec<f32> = want_bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect();
    assert_eq!(got.len(), want.len(), "{name}: length");
    for (i, (g, w)) in got.iter().zip(&want).enumerate() {
        // Both sides are finite and non-negative here, so the monotone f32 bit pattern is an
        // ULP count; a sign straddle would make this meaningless.
        assert!(
            g.is_finite() && w.is_finite() && *g >= 0.0 && *w >= 0.0,
            "{name}[{i}]: {g} vs {w}"
        );
        let d = (i64::from(g.to_bits()) - i64::from(w.to_bits())).unsigned_abs();
        assert!(
            d <= u64::from(tol),
            "{name}[{i}]: {g} vs {w} is {d} ulp > {tol}"
        );
    }
}

/// The same 8x6 RGB u8 HWC gradient `gen_goldens` starts from.
fn gradient_8x6() -> Vec<u8> {
    let mut px = Vec::with_capacity(8 * 6 * 3);
    for y in 0..6u32 {
        for x in 0..8u32 {
            px.push((x * 32) as u8);
            px.push((y * 40) as u8);
            px.push(((x + y) * 16) as u8);
        }
    }
    px
}

fn dequantized() -> Vec<f32> {
    let mut chw = vec![0.0f32; 3 * 6 * 8];
    kernels::cast_u8_hwc_to_f32_chw(&gradient_8x6(), 6, 8, 3, &mut chw);
    chw
}

// --- goldens ------------------------------------------------------------------------------

#[test]
fn dequantize_matches_the_golden() {
    assert_golden("dequantize_8x6_rgb", &dequantized());
}

#[test]
fn resize_matches_the_golden() {
    let mut small = vec![0.0f32; 3 * 3 * 4];
    kernels::resize_bilinear(&dequantized(), 8, 6, 3, 4, 3, &mut small);
    assert_golden("resize_bilinear_8x6_to_4x3", &small);
}

#[test]
fn crop_matches_the_golden() {
    let rect = Rect {
        x: 2,
        y: 1,
        width: 4,
        height: 4,
    };
    let mut cropped = vec![0.0f32; 3 * 4 * 4];
    kernels::crop(&dequantized(), 8, 6, 3, rect, &mut cropped);
    assert_golden("crop_8x6_at_2_1_4x4", &cropped);
}

/// The one golden with a tolerance: the kernel evaluates the 2.4 power as
/// `es_math::approx::exp(2.4 * ln t)` because `DET-010` forbids `powf` in an observation
/// kernel, so it cannot be bit-equal to the f64 reference formula. 7 ULP is the measured
/// worst case over all 256 entries, declared in the sidecar, not a margin chosen to pass.
#[test]
fn srgb_lut_matches_the_golden() {
    assert_golden("srgb_to_linear_lut256", &kernels::srgb_to_linear_lut());
}

#[test]
fn normalize_matches_the_golden() {
    let mut small = vec![0.0f32; 3 * 3 * 4];
    kernels::resize_bilinear(&dequantized(), 8, 6, 3, 4, 3, &mut small);
    let mut norm = vec![0.0f32; 3 * 3 * 4];
    kernels::normalize_mean_std(&small, 12, &MEAN, &STD, &mut norm);
    assert_golden("normalize_imagenet_4x3", &norm);
}

#[test]
fn history_window_matches_the_golden() {
    let (slot, depth) = (4usize, 4usize);
    let mut ring = vec![0.0f32; slot * depth];
    for i in 0..3usize {
        let f = i as f32;
        kernels::history_push(&mut ring, slot, depth, i, &[f, f + 0.5, f + 1.0, f + 1.5]);
    }
    let mut win = vec![0.0f32; slot * 2];
    kernels::window_gather(&ring, slot, depth, 2, 3, 2, 1, &mut win);
    assert_golden("history_window_n2_s1", &win);
}

// --- the plan, end to end -----------------------------------------------------------------

fn sensor() -> StableId {
    StableId::from_path("cam_front")
}

fn spec_8x6() -> ImageSpec {
    ImageSpec {
        width: 8,
        height: 6,
        channels: ChannelFormat::Rgb,
        dtype: ImageDType::U8,
        color_space: ColorSpace::SRgb,
        camera_model: CameraModel::Pinhole,
        intrinsics: Intrinsics::new(6.0, 6.0, 4.0, 3.0),
        extrinsics: Pose::IDENTITY,
        distortion: DistortionModel::None,
        shutter: ShutterModel::Global,
        exposure: Duration::from_micros(500),
        rate_hz: 30.0,
        depth_scale: None,
    }
}

fn ty(elem: ElemType, shape: [u64; 3], unit: Unit, spec: ImageSpec) -> PortType {
    PortType {
        elem,
        shape: Shape::new(shape),
        unit,
        frame: Frame::Camera(sensor()),
        time: TimeRef::Sensor {
            id: sensor(),
            align: Align::Hold,
        },
        image: Some(spec),
    }
}

/// `ImageInput(8x6 u8 HWC)` -> `Dequantize` -> `Resize(4x3)` -> `Normalize(ImageNet)`.
fn chain() -> ObservationIr {
    let src = spec_8x6();
    let deq = ImageSpec {
        dtype: ImageDType::F32,
        ..src
    };
    let small = deq.resized(4, 3, true);

    let t_in = ty(ElemType::U8, [6, 8, 3], Unit::Pixel, src);
    let t_deq = ty(ElemType::F32, [3, 6, 8], Unit::Pixel, deq);
    let t_small = ty(ElemType::F32, [3, 3, 4], Unit::Pixel, small);
    let t_out = ty(
        ElemType::F32,
        [3, 3, 4],
        Unit::Normalized { lo: -3.0, hi: 3.0 },
        small,
    );

    let mut ir = ObservationIr::new(1, [0u8; 32]);
    ir.graph.insert(
        NodeId(0),
        ObservationNode::ImageInput {
            sensor: sensor(),
            io: Io::source(t_in.clone()),
        },
    );
    ir.graph.insert(
        NodeId(1),
        ObservationNode::Dequantize {
            io: Io::unary(t_in, t_deq.clone()),
        },
    );
    ir.graph.insert(
        NodeId(2),
        ObservationNode::Resize {
            width: 4,
            height: 3,
            filter: ResizeFilter::Bilinear,
            rescale_intrinsics: true,
            io: Io::unary(t_deq, t_small.clone()),
        },
    );
    ir.graph.insert(
        NodeId(3),
        ObservationNode::Normalize {
            stats: NormalizeStats::MeanStd {
                mean: MEAN.iter().map(|v| f64::from(*v)).collect(),
                std: STD.iter().map(|v| f64::from(*v)).collect(),
            },
            io: Io::unary(t_small, t_out.clone()),
        },
    );
    for a in 0..3u32 {
        ir.graph.connect(NodeId(a), OUT, NodeId(a + 1), &in_port(0));
    }
    ir.graph.outputs.push(PortRef::new(NodeId(3), OUT));
    ir.outputs.insert(
        "rgb_front".to_owned(),
        ObservationOutput {
            port: PortRef::new(NodeId(3), OUT),
            ty: t_out,
        },
    );
    ir
}

#[test]
fn the_plan_reproduces_the_goldens_end_to_end() {
    let ir = chain();
    assert!(ir.validate().is_empty(), "{:?}", ir.validate());
    let mut plan = CpuPlan::compile(&ir, PlanMode::Debug).expect("compiles");
    assert_eq!(plan.steps.len(), 3); // dequantize, resize, normalize
    assert_eq!(plan.inputs.len(), 1);

    let px = gradient_8x6();
    let mut inputs = BTreeMap::new();
    inputs.insert(
        sensor().to_string(),
        TensorRef::new(ElemType::U8, [6, 8, 3], &px),
    );
    let out = plan.run(&inputs).expect("runs");

    let rgb = &out["rgb_front"];
    assert_eq!(rgb.dtype, ElemType::F32);
    assert_eq!(rgb.shape, vec![3, 3, 4]);
    assert_eq!(rgb.data, golden("normalize_imagenet_4x3"));
}

#[test]
fn compiler_hash_separates_the_two_plans() {
    let ir = chain();
    let debug = CpuPlan::compile(&ir, PlanMode::Debug).unwrap();
    let release = CpuPlan::compile(&ir, PlanMode::Release).unwrap();
    assert_ne!(debug.compiler_hash(), release.compiler_hash());
    // Spec 11.5 on this path: neither plan aliases, so both can show every node's value.
    assert_eq!(debug.arena_elems, release.arena_elems);
    assert!(debug.buffer_of(NodeId(2)).is_some());
}

/// `StateInput([2] f32)` -> `TemporalWindow(n = 2, stride = 1)`, the smallest graph that
/// carries plan state across `run` calls.
fn windowed() -> ObservationIr {
    let raw = PortType {
        elem: ElemType::F32,
        shape: Shape::new([2]),
        unit: Unit::Angle,
        frame: Frame::Joint(sensor()),
        time: TimeRef::Sensor {
            id: sensor(),
            align: Align::Hold,
        },
        image: None,
    };
    let win = PortType {
        shape: Shape::new([2, 2]),
        time: TimeRef::Window {
            base: Box::new(raw.time.clone()),
            n: 2,
            stride: 1,
        },
        ..raw.clone()
    };
    let mut ir = ObservationIr::new(1, [0u8; 32]);
    ir.temporal
        .history
        .insert(sensor(), es_ir::observation::History { depth: 2 });
    ir.graph.insert(
        NodeId(0),
        ObservationNode::StateInput {
            source: sensor(),
            io: Io::source(raw.clone()),
        },
    );
    ir.graph.insert(
        NodeId(1),
        ObservationNode::TemporalWindowNode {
            window: es_ir::observation::TemporalWindow {
                n_steps: 2,
                stride: 1,
                align: Align::Hold,
            },
            io: Io::unary(raw, win.clone()),
        },
    );
    ir.graph.connect(NodeId(0), OUT, NodeId(1), &in_port(0));
    ir.graph.outputs.push(PortRef::new(NodeId(1), OUT));
    ir.outputs.insert(
        "joint_state".to_owned(),
        ObservationOutput {
            port: PortRef::new(NodeId(1), OUT),
            ty: win,
        },
    );
    ir
}

fn run_state(plan: &mut CpuPlan, v: [f32; 2]) -> Vec<u8> {
    let bytes: Vec<u8> = v.iter().flat_map(|x| x.to_le_bytes()).collect();
    let inputs = BTreeMap::from([(
        sensor().to_string(),
        TensorRef::new(ElemType::F32, [2], &bytes),
    )]);
    plan.run(&inputs).expect("runs")["joint_state"].data.clone()
}

/// P-M2-R1. A `run` after `reset` must equal a fresh plan's first `run`: the rings are the
/// only state, and an episode boundary ends the stream (spec 7.5 layer 1, §10.4).
#[test]
fn reset_returns_the_plan_to_a_freshly_compiled_one() {
    let ir = windowed();
    let mut plan = CpuPlan::compile(&ir, PlanMode::Release).expect("compiles");
    for v in [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]] {
        let _ = run_state(&mut plan, v);
    }
    let leaked = run_state(&mut plan, [7.0, 8.0]);
    plan.reset();
    let after_reset = run_state(&mut plan, [7.0, 8.0]);

    let mut fresh = CpuPlan::compile(&ir, PlanMode::Release).expect("compiles");
    let first = run_state(&mut fresh, [7.0, 8.0]);
    assert_eq!(after_reset, first, "reset must clear every ring");
    assert_ne!(
        leaked, first,
        "the fixture must be history-sensitive, or the test proves nothing"
    );
    assert!(plan.rings.values().all(|r| r.pushed == 1 && r.cursor == 0));
}

/// P-M2-R2 / INV-15. A `training_only` `Augment` is an identity pass-through on this path,
/// so a converted `LeRobot` graph that carries one still plans and still runs.
#[test]
fn a_training_only_augment_is_an_identity_pass_through() {
    let plain = chain();
    let mut ir = chain();
    let out_ty = ir.outputs["rgb_front"].ty.clone();
    ir.graph.insert(
        NodeId(4),
        ObservationNode::Augment {
            kind: es_ir::observation::AugmentKind::GaussianNoise { sigma: 0.1 },
            training_only: true,
            io: Io::unary(out_ty.clone(), out_ty.clone()),
        },
    );
    ir.graph.connect(NodeId(3), OUT, NodeId(4), &in_port(0));
    ir.graph.outputs.clear();
    ir.graph.outputs.push(PortRef::new(NodeId(4), OUT));
    ir.outputs.insert(
        "rgb_front".to_owned(),
        ObservationOutput {
            port: PortRef::new(NodeId(4), OUT),
            ty: out_ty,
        },
    );
    assert!(ir.validate().is_empty(), "{:?}", ir.validate());

    let mut with_augment = CpuPlan::compile(&ir, PlanMode::Release).expect("compiles");
    let mut without = CpuPlan::compile(&plain, PlanMode::Release).expect("compiles");
    assert_eq!(
        with_augment.steps.len(),
        without.steps.len(),
        "an identity node must not emit a step"
    );

    let px = gradient_8x6();
    let inputs = BTreeMap::from([(
        sensor().to_string(),
        TensorRef::new(ElemType::U8, [6, 8, 3], &px),
    )]);
    assert_eq!(
        with_augment.run(&inputs).expect("runs")["rgb_front"],
        without.run(&inputs).expect("runs")["rgb_front"]
    );
}

/// An `Augment` that is *not* `training_only` would have to actually run here, and there is
/// no augmentation kernel on this path: a diagnostic, never a silent identity.
#[test]
fn an_augment_that_is_not_training_only_is_a_diagnostic() {
    let mut ir = chain();
    let out_ty = ir.outputs["rgb_front"].ty.clone();
    ir.graph.insert(
        NodeId(4),
        ObservationNode::Augment {
            kind: es_ir::observation::AugmentKind::GaussianNoise { sigma: 0.1 },
            training_only: false,
            io: Io::unary(out_ty.clone(), out_ty),
        },
    );
    ir.graph.connect(NodeId(3), OUT, NodeId(4), &in_port(0));
    let errs = CpuPlan::compile(&ir, PlanMode::Release).unwrap_err();
    assert!(
        errs.iter()
            .any(|d| d.code.as_str() == "OBS-041" || d.code.as_str() == "COMPILE-002"),
        "{errs:?}"
    );
}

#[test]
fn an_unsupported_node_is_a_diagnostic_not_a_silent_no_op() {
    let mut ir = chain();
    let small = ImageSpec {
        dtype: ImageDType::F32,
        ..spec_8x6()
    }
    .resized(4, 3, true);
    let gray = ImageSpec {
        channels: ChannelFormat::Gray,
        ..small
    };
    let unit = Unit::Normalized { lo: -3.0, hi: 3.0 };
    let t = ty(ElemType::F32, [3, 3, 4], unit.clone(), small);
    ir.graph.insert(
        NodeId(4),
        ObservationNode::ToGray {
            io: Io::unary(t, ty(ElemType::F32, [1, 3, 4], unit, gray)),
        },
    );
    ir.graph.connect(NodeId(3), OUT, NodeId(4), &in_port(0));
    let errs = CpuPlan::compile(&ir, PlanMode::Debug).unwrap_err();
    assert!(
        errs.iter().any(|d| d.code.as_str() == "COMPILE-002"),
        "{errs:?}"
    );
}

// --- properties ---------------------------------------------------------------------------

proptest! {
    /// A resize of a constant image is that constant — to within 2 ulp.
    ///
    /// No neighbour leaks in at the border, which is the classic half-pixel bug. It is not
    /// *bit*-exact, and deliberately so: the taps are combined as `l0 * a + l1 * b` with
    /// `l0 = 1 - l1`, which is PyTorch's association and does not sum the weights to exactly
    /// 1 in f32. Matching PyTorch bit for bit is the contract (spec 7.7); an exact-on-
    /// constants association would be a different kernel.
    #[test]
    fn resize_of_a_constant_is_constant(
        v in -10.0f32..10.0,
        sw in 1usize..17,
        sh in 1usize..17,
        dw in 1usize..17,
        dh in 1usize..17,
    ) {
        let src = vec![v; 2 * sh * sw];
        let mut dst = vec![f32::NAN; 2 * dh * dw];
        kernels::resize_bilinear(&src, sw, sh, 2, dw, dh, &mut dst);
        let tol = 2.0 * f32::EPSILON * v.abs();
        prop_assert!(dst.iter().all(|x| (*x - v).abs() <= tol), "{dst:?}");
    }

    /// `crop(crop(x, a), b) == crop(x, a o b)` in pixels, and `ImageSpec::cropped` chained
    /// gives the same intrinsics as the combined rectangle (`INV-14`).
    #[test]
    fn crop_of_crop_is_one_crop(
        ax in 0u32..4, ay in 0u32..3, bx in 0u32..2, by in 0u32..2,
        bw in 1u32..3, bh in 1u32..3,
    ) {
        let (w, h, c) = (8usize, 6usize, 3usize);
        let a = Rect { x: ax, y: ay, width: w as u32 - ax, height: h as u32 - ay };
        prop_assume!(bx + bw <= a.width && by + bh <= a.height);
        let b = Rect { x: bx, y: by, width: bw, height: bh };
        let combined = Rect { x: a.x + b.x, y: a.y + b.y, width: b.width, height: b.height };

        let src = dequantized();
        let mut mid = vec![0.0f32; c * a.height as usize * a.width as usize];
        kernels::crop(&src, w, h, c, a, &mut mid);
        let mut twice = vec![0.0f32; c * bh as usize * bw as usize];
        kernels::crop(&mid, a.width as usize, a.height as usize, c, b, &mut twice);
        let mut once = vec![0.0f32; c * bh as usize * bw as usize];
        kernels::crop(&src, w, h, c, combined, &mut once);
        prop_assert_eq!(&twice, &once);

        let spec = spec_8x6();
        let chained = spec.cropped(a, true).cropped(b, true);
        let direct = spec.cropped(combined, true);
        prop_assert_eq!(chained.intrinsics, direct.intrinsics);
        prop_assert_eq!((chained.width, chained.height), (direct.width, direct.height));
    }

    /// Whatever the camera geometry, the chain compiles and runs, and the plan's crop
    /// rectangle is the one the type system used.
    #[test]
    fn the_centre_crop_plan_agrees_with_the_propagated_spec(cw in 1u32..8, ch in 1u32..6) {
        let src = spec_8x6();
        let deq = ImageSpec { dtype: ImageDType::F32, ..src };
        let rect = CropMode::Center { width: cw, height: ch };
        let cropped = deq.cropped(
            Rect { x: (8 - cw) / 2, y: (6 - ch) / 2, width: cw, height: ch },
            true,
        );

        let t_in = ty(ElemType::U8, [6, 8, 3], Unit::Pixel, src);
        let t_deq = ty(ElemType::F32, [3, 6, 8], Unit::Pixel, deq);
        let t_out = ty(
            ElemType::F32,
            [3, u64::from(ch), u64::from(cw)],
            Unit::Pixel,
            cropped,
        );

        let mut ir = ObservationIr::new(1, [0u8; 32]);
        ir.graph.insert(NodeId(0), ObservationNode::ImageInput {
            sensor: sensor(), io: Io::source(t_in.clone()) });
        ir.graph.insert(NodeId(1), ObservationNode::Dequantize {
            io: Io::unary(t_in, t_deq.clone()) });
        ir.graph.insert(NodeId(2), ObservationNode::Crop {
            mode: rect, rescale_intrinsics: true, io: Io::unary(t_deq, t_out.clone()) });
        ir.graph.connect(NodeId(0), OUT, NodeId(1), &in_port(0));
        ir.graph.connect(NodeId(1), OUT, NodeId(2), &in_port(0));
        ir.graph.outputs.push(PortRef::new(NodeId(2), OUT));
        ir.outputs.insert("rgb".to_owned(), ObservationOutput {
            port: PortRef::new(NodeId(2), OUT), ty: t_out });

        let mut plan = CpuPlan::compile(&ir, PlanMode::Release).expect("compiles");
        let px = gradient_8x6();
        let mut inputs = BTreeMap::new();
        inputs.insert(sensor().to_string(), TensorRef::new(ElemType::U8, [6, 8, 3], &px));
        let out = plan.run(&inputs).expect("runs");
        prop_assert_eq!(
            out["rgb"].data.len(),
            3 * cw as usize * ch as usize * 4
        );
        prop_assert_eq!(
            ir.propagate_image_specs().unwrap()[&PortRef::new(NodeId(2), OUT)].intrinsics,
            cropped.intrinsics
        );
    }
}

// --- packet M7/T6: the training_only chain, and what the Release plan does with it ---------

/// `chain()` with `Pad(pad) -> Augment{RandomCrop w x h, training_only}` appended, the
/// fixture's shape at the fixture's scale: the chain ends at the declared output.
fn padded_random_crop(pad: u32, w: u32, h: u32) -> ObservationIr {
    let mut ir = chain();
    let out_ty = ir.outputs["rgb_front"].ty.clone();
    let spec = out_ty.image.expect("the image port carries a spec");
    let padded_spec = ImageSpec {
        width: spec.width + 2 * pad,
        height: spec.height + 2 * pad,
        intrinsics: Intrinsics {
            cx: spec.intrinsics.cx + f64::from(pad),
            cy: spec.intrinsics.cy + f64::from(pad),
            ..spec.intrinsics
        },
        ..spec
    };
    let mut padded_ty = out_ty.clone();
    padded_ty.shape = Shape::new([
        3,
        u64::from(padded_spec.height),
        u64::from(padded_spec.width),
    ]);
    padded_ty.image = Some(padded_spec);
    let mut cropped_ty = out_ty.clone();
    cropped_ty.shape = Shape::new([3, u64::from(h), u64::from(w)]);
    cropped_ty.image = Some(padded_spec.cropped(
        Rect {
            x: (padded_spec.width - w) / 2,
            y: (padded_spec.height - h) / 2,
            width: w,
            height: h,
        },
        true,
    ));

    ir.graph.insert(
        NodeId(4),
        ObservationNode::Pad {
            left: pad,
            top: pad,
            right: pad,
            bottom: pad,
            io: Io::unary(out_ty, padded_ty.clone()),
        },
    );
    ir.graph.insert(
        NodeId(5),
        ObservationNode::Augment {
            kind: es_ir::observation::AugmentKind::RandomCrop {
                width: w,
                height: h,
            },
            training_only: true,
            io: Io::unary(padded_ty, cropped_ty.clone()),
        },
    );
    ir.graph.connect(NodeId(3), OUT, NodeId(4), &in_port(0));
    ir.graph.connect(NodeId(4), OUT, NodeId(5), &in_port(0));
    ir.graph.outputs.clear();
    ir.graph.outputs.push(PortRef::new(NodeId(5), OUT));
    ir.outputs.insert(
        "rgb_front".to_owned(),
        ObservationOutput {
            port: PortRef::new(NodeId(5), OUT),
            ty: cropped_ty,
        },
    );
    ir
}

fn run_chain(ir: &ObservationIr) -> Tensor {
    let mut plan = CpuPlan::compile(ir, PlanMode::Release).expect("compiles");
    let px = gradient_8x6();
    let inputs = BTreeMap::from([(
        sensor().to_string(),
        TensorRef::new(ElemType::U8, [6, 8, 3], &px),
    )]);
    plan.run(&inputs).expect("runs")["rgb_front"].clone()
}

/// Oracle 2 of packet M7/T6. `Pad(p) -> RandomCrop{w,h}(training_only)` with a symmetric pad
/// hands the network the un-augmented document's pixels, bit for bit, and the crop carries
/// `Crop`'s intrinsics transform (INV-14): pad moves the principal point by `+p`, the centre
/// crop moves it back. A `RandomCrop` whose input already is `w x h` stays the identity it
/// was, so INV-15's structure is untouched for every document that has no pad.
#[test]
fn a_training_only_random_crop_is_a_centre_crop_in_release() {
    let plain = chain();
    let ir = padded_random_crop(2, 4, 3);
    assert!(ir.validate().is_empty(), "{:?}", ir.validate());

    assert_eq!(
        run_chain(&ir),
        run_chain(&plain),
        "the padded, centre-cropped Release plan does not reproduce the un-augmented pixels"
    );

    let plan = CpuPlan::compile(&ir, PlanMode::Release).expect("compiles");
    // Two steps more than the plain plan: the pad and the centre crop. The crop is a real
    // step, with the centred rectangle -- which for a symmetric pad is `(p, p)`.
    assert_eq!(plan.steps.len(), 5);
    let crop = plan
        .steps
        .iter()
        .find(|s| s.node == NodeId(5))
        .expect("the RandomCrop lowered to a step");
    assert_eq!(
        crop.op,
        Op::Crop {
            sw: 8,
            sh: 7,
            c: 3,
            rect: Rect {
                x: 2,
                y: 2,
                width: 4,
                height: 3,
            },
        }
    );
    // INV-14: the spec the plan carries out of the crop is the spec that went into the pad.
    let before = CpuPlan::compile(&plain, PlanMode::Release)
        .expect("compiles")
        .image_specs[&NodeId(3)];
    assert_eq!(plan.image_specs[&NodeId(5)], before);

    // ...and with no pad the node is the identity pass-through it has always been.
    let mut identity = chain();
    let out_ty = identity.outputs["rgb_front"].ty.clone();
    identity.graph.insert(
        NodeId(4),
        ObservationNode::Augment {
            kind: es_ir::observation::AugmentKind::RandomCrop {
                width: 4,
                height: 3,
            },
            training_only: true,
            io: Io::unary(out_ty.clone(), out_ty.clone()),
        },
    );
    identity
        .graph
        .connect(NodeId(3), OUT, NodeId(4), &in_port(0));
    identity.graph.outputs.clear();
    identity.graph.outputs.push(PortRef::new(NodeId(4), OUT));
    identity.outputs.insert(
        "rgb_front".to_owned(),
        ObservationOutput {
            port: PortRef::new(NodeId(4), OUT),
            ty: out_ty,
        },
    );
    let plan = CpuPlan::compile(&identity, PlanMode::Release).expect("compiles");
    assert_eq!(plan.steps.len(), 3, "a same-size RandomCrop emitted a step");
    assert_eq!(run_chain(&identity), run_chain(&plain));
}

/// `Pad` is replicate: the border repeats the edge pixel, and the interior is the input.
// A pad copies bytes, so exact equality is the property under test.
#[allow(clippy::float_cmp)]
#[test]
fn pad_replicates_the_edge() {
    let ir = padded_random_crop(2, 8, 7);
    let padded = run_chain(&ir);
    let plain = run_chain(&chain());
    assert_eq!(padded.shape, vec![3, 7, 8]);
    let at = |t: &Tensor, c: usize, y: usize, x: usize, w: usize| -> f32 {
        let i = (c * t.shape[1] as usize * w + y * w + x) * 4;
        f32::from_le_bytes([t.data[i], t.data[i + 1], t.data[i + 2], t.data[i + 3]])
    };
    for c in 0..3 {
        for y in 0..3 {
            for x in 0..4 {
                assert_eq!(
                    at(&padded, c, y + 2, x + 2, 8),
                    at(&plain, c, y, x, 4),
                    "the interior moved at {c} {y} {x}"
                );
            }
        }
        // Corners and edges replicate.
        assert_eq!(at(&padded, c, 0, 0, 8), at(&plain, c, 0, 0, 4));
        assert_eq!(at(&padded, c, 6, 7, 8), at(&plain, c, 2, 3, 4));
        assert_eq!(at(&padded, c, 0, 3, 8), at(&plain, c, 0, 1, 4));
    }
}

/// The boundary rule (packet M7/T6): the chain is the contiguous run of `training_only`
/// nodes ending at a declared output. Anything else is refused by name, because the trainer
/// would otherwise be told to apply less than the author declared.
#[test]
fn the_augmentation_chain_is_found_or_refused_by_name() {
    let plain = chain();
    assert!(
        es_compile::plan::augmentation_chains(&plain)
            .expect("no augmentation")
            .is_empty(),
        "a document with no Augment node has no chain"
    );

    let ir = padded_random_crop(2, 4, 3);
    let chains = es_compile::plan::augmentation_chains(&ir).expect("one chain");
    assert_eq!(chains.len(), 1);
    assert_eq!(chains["rgb_front"].len(), 1);
    assert_eq!(chains["rgb_front"][0].node, NodeId(5));

    // A `training_only` node behind a non-augment node is not on the chain: it would be an
    // identity on *every* path, and nothing would ever apply it.
    let mut buried = padded_random_crop(2, 4, 3);
    let out_ty = buried.outputs["rgb_front"].ty.clone();
    buried.graph.insert(
        NodeId(6),
        ObservationNode::Normalize {
            stats: NormalizeStats::Range { lo: 0.0, hi: 1.0 },
            io: Io::unary(out_ty.clone(), out_ty.clone()),
        },
    );
    buried.graph.connect(NodeId(5), OUT, NodeId(6), &in_port(0));
    buried.graph.outputs.clear();
    buried.graph.outputs.push(PortRef::new(NodeId(6), OUT));
    buried.outputs.insert(
        "rgb_front".to_owned(),
        ObservationOutput {
            port: PortRef::new(NodeId(6), OUT),
            ty: out_ty,
        },
    );
    let diags = es_compile::plan::augmentation_chains(&buried).expect_err("refused");
    assert!(
        diags.iter().any(|d| d.code.as_str() == "COMPILE-007"),
        "{diags:?}"
    );

    // ...and the IR's *other* spelling of a per-sample offset is on the chain too: the demo's
    // document uses it, because it is the one `es-ir` propagates geometry for (the deviation
    // in design note `training-recipe.md` section 13). Its Release lowering is the centred
    // rectangle it has always been.
    let mut cropped = chain();
    let out_ty = cropped.outputs["rgb_front"].ty.clone();
    let spec = out_ty.image.expect("an image port");
    let mut small_ty = out_ty.clone();
    let rect = Rect {
        x: (spec.width - 2) / 2,
        y: (spec.height - 2) / 2,
        width: 2,
        height: 2,
    };
    small_ty.shape = Shape::new([3, 2, 2]);
    small_ty.image = Some(spec.cropped(rect, true));
    cropped.graph.insert(
        NodeId(4),
        ObservationNode::Crop {
            mode: CropMode::Random {
                width: 2,
                height: 2,
            },
            rescale_intrinsics: true,
            io: Io::unary(out_ty, small_ty.clone()),
        },
    );
    cropped
        .graph
        .connect(NodeId(3), OUT, NodeId(4), &in_port(0));
    cropped.graph.outputs.clear();
    cropped.graph.outputs.push(PortRef::new(NodeId(4), OUT));
    cropped.outputs.insert(
        "rgb_front".to_owned(),
        ObservationOutput {
            port: PortRef::new(NodeId(4), OUT),
            ty: small_ty,
        },
    );
    assert!(cropped.validate().is_empty(), "{:?}", cropped.validate());
    let chains = es_compile::plan::augmentation_chains(&cropped).expect("one chain");
    assert_eq!(
        chains["rgb_front"],
        vec![es_compile::plan::AugmentStep {
            node: NodeId(4),
            kind: es_ir::observation::AugmentKind::RandomCrop {
                width: 2,
                height: 2
            },
        }]
    );
    let plan = CpuPlan::compile(&cropped, PlanMode::Release).expect("compiles");
    assert!(
        plan.steps.iter().any(|s| s.op
            == Op::Crop {
                sw: 4,
                sh: 3,
                c: 3,
                rect,
            }),
        "the Release plan is not the centred rectangle: {:?}",
        plan.steps
    );
}
