[package]
name = "es-env"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
es-core = { workspace = true }
es-math = { workspace = true }
es-ir = { workspace = true }
es-assets = { workspace = true }
es-physics-core = { workspace = true }
es-compile = { workspace = true }
es-policy = { workspace = true }
es-safety = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
