//! Oracle for the rollout binding (packet M8/S4a): `Rollout` *is* the evaluation loop.
//!
//! The claim under test is the one `docs/design/rl-continuation.md` rule 2 makes — a trainer
//! stepping `es_native.Rollout` steps the same runtime `es eval run` does, through the same
//! Safety Plane — so this drives both and compares them bitwise:
//!
//! * `Rollout::<6, 16>` on the committed SO-101 documents, 100 control steps of a fixed
//!   scripted control, against
//! * a hand-rolled `Env` + `CpuPlan` + `SafetyPlane` loop written here in the order
//!   `es_eval::runner::run_episode` runs it (`observe -> observe_state -> heartbeat ->
//!   validate -> step`), and
//! * `tests/golden/rollout/so101_100steps.json`, which `python -m es.selfcheck --env` compares
//!   the pyclass against, so the Rust struct and the Python class are pinned to one trace.
//!
//! `--ignored`: it needs `MuJoCo` through `ES_PYTHON` (spec 1.4's reference backend). With
//! `ES_GENERATE_GOLDENS=1` it writes the golden instead of asserting against it.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use es_compile::{CpuPlan, PlanMode, TensorRef};
use es_core::{PhysTick, TickRate};
use es_env::scheduler::BatchDomains;
use es_env::Env;
use es_eval::runner::{capture, input_sources, joint_state};
use es_eval::LightOverride;
use es_ir::deployment::Micros;
use es_ir::observation::ObservationIr;
use es_native::rollout::Rollout;
use es_physics_backend::MuJoCoCpuBackend;
use es_physics_core::backend::{PhysicsBackend, StateView};
use es_safety::{ActionChunk, SafetyPlane};
use serde::{Deserialize, Serialize};

/// The demo's joint count and the horizon its Deployment IR declares. The rollout fills one
/// row of that chunk per control tick (horizon 1 in the trainer's sense) — `SafetyPlane` still
/// wants the document's own `H`.
const NJ: usize = 6;
const H: usize = 16;
const STEPS: u64 = 100;
const N_ENVS: u32 = 2;
const SEED: u64 = 7;
/// One env is reset mid-run so the episode boundary — `begin_episode` on that env's plane and
/// `CpuPlan::reset` on its rings (packet P-M7-R1) — is part of the trace rather than a code
/// path nobody ran.
const RESET_AT: u64 = 50;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/es-py is two levels under the repo root")
        .to_path_buf()
}

fn read(rel: &str) -> String {
    let path = repo_root().join(rel);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

/// The header that says where `observation-state.toml` comes from, so nobody edits it by hand.
const OBS_HEADER: &str = "\
# The demo's Observation IR (tests/fixtures/visible-learning/observation.toml) with the camera
# branch removed -- generated by `cargo test -p es-py rollout_matches_es_eval_loop -- --ignored`
# under `ES_GENERATE_GOLDENS=1`, never typed in.
#
# Why it exists (packet M8/S4a): an `ImageInput` is served by a renderer, and `es-py` links
# none -- `es_eval::runner::capture` refuses an image input by name there rather than feeding
# the policy zeros. RL continuation reads proprioceptive state anyway
# (`docs/design/rl-continuation.md` section 5), so this is the demo's two state branches,
# `joint_state` and `sim_cube_pose`, and nothing else. `task_ref` is untouched: it is still an
# observation of the same Task IR, with the same hashes behind it.
";

/// The demo observation minus every output that carries an `ImageSpec`, and every node that
/// only fed one.
fn state_only(mut obs: ObservationIr) -> ObservationIr {
    obs.outputs.retain(|_, o| o.ty.image.is_none());
    let mut keep: Vec<es_ir::graph::NodeId> = obs.outputs.values().map(|o| o.port.node).collect();
    // Backwards closure over the edges: a node is kept iff something kept is fed by it.
    let mut i = 0;
    while i < keep.len() {
        let node = keep[i];
        for e in &obs.graph.edges {
            if e.to.node == node && !keep.contains(&e.from.node) {
                keep.push(e.from.node);
            }
        }
        i += 1;
    }
    obs.graph.nodes.retain(|id, _| keep.contains(id));
    obs.graph
        .edges
        .retain(|e| keep.contains(&e.from.node) && keep.contains(&e.to.node));
    obs
}

/// The four documents the rollout is built from, as text.
fn documents() -> (String, String, String, String) {
    let task = read("tests/fixtures/visible-learning/task.toml");
    let deployment = read("tests/fixtures/visible-learning/deployment.toml");
    let scene = read("tests/fixtures/mjcf/so101_pick_place.xml");

    let demo = es_ir::serial::observation_from_toml(&read(
        "tests/fixtures/visible-learning/observation.toml",
    ))
    .expect("the demo observation parses");
    let body = es_ir::serial::observation_to_toml(&state_only(demo)).expect("serializes");
    let observation = format!("{OBS_HEADER}{body}");
    let fixture = repo_root().join("crates/es-py/tests/fixtures/observation-state.toml");
    if std::env::var("ES_GENERATE_GOLDENS").as_deref() == Ok("1") {
        std::fs::create_dir_all(fixture.parent().expect("has a parent")).expect("mkdir");
        std::fs::write(&fixture, &observation).expect("write the observation fixture");
    } else {
        let committed = std::fs::read_to_string(&fixture)
            .unwrap_or_else(|e| panic!("{}: {e}", fixture.display()));
        assert_eq!(
            committed.replace("\r\n", "\n"),
            observation,
            "{} has drifted from the demo observation it is derived from; regenerate it with \
             ES_GENERATE_GOLDENS=1",
            fixture.display()
        );
    }
    (task, observation, deployment, scene)
}

/// The scripted control, in actuator units (joint position targets, rad).
///
/// Exact in binary f64 and free of transcendentals, so the only thing that can move the golden
/// is the runtime. A slow triangle wave every joint follows, plus one 0.5 rad kick every tenth
/// step that the envelope has to clamp — without it the whole trace would be
/// `ActionSource::Policy` and the plane would be along for the ride.
fn scripted(step: u64, env: usize, joint: usize) -> f64 {
    let phase = (step as usize + env * 5 + joint * 3) % 40;
    let tri = if phase < 20 { phase } else { 40 - phase };
    let base = (tri as f64 - 10.0) / 100.0;
    if step % 10 == 0 && joint == (step / 10) as usize % NJ {
        base + 0.5
    } else {
        base
    }
}

fn actions(step: u64, n_envs: usize) -> Vec<f64> {
    (0..n_envs)
        .flat_map(|e| (0..NJ).map(move |j| scripted(step, e, j)))
        .collect()
}

/// One control step of the trace. Every number is one both loops produce.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
struct StepRec {
    /// `n_envs * nq`, row-major by env.
    qpos: Vec<f64>,
    /// The Observation IR's output ports, `n_envs * dim` each.
    observations: BTreeMap<String, Vec<f64>>,
    /// What reached the actuator: the plane's output, not the sample.
    executed: Vec<f64>,
    /// `EventSet::bits()` per env.
    events: Vec<u32>,
    rewards: Vec<f64>,
    dones: Vec<bool>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq)]
struct Trace {
    schema: u32,
    n_envs: u32,
    seed: u64,
    steps: Vec<StepRec>,
}

/// One env's row of the batch state — the same view `es_native::rollout` hands the capture.
fn env_view<'a>(state: &StateView<'a>, env: usize) -> StateView<'a> {
    let row = |values: &'a [f64]| {
        let stride = values.len() / state.n_envs.max(1) as usize;
        values
            .get(env * stride..(env + 1) * stride)
            .unwrap_or_default()
    };
    StateView {
        n_envs: 1,
        tick: state.tick,
        qpos: row(state.qpos),
        qvel: row(state.qvel),
        act: row(state.act),
        sensordata: row(state.sensordata),
        xpos: row(state.xpos),
        xquat: row(state.xquat),
    }
}

fn f32s(t: &es_compile::Tensor) -> Vec<f64> {
    t.data
        .chunks_exact(4)
        .map(|c| f64::from(f32::from_le_bytes([c[0], c[1], c[2], c[3]])))
        .collect()
}

/// `es eval run`'s loop, written out by hand: the twin the binding is judged against.
fn hand_rolled(task: &str, observation: &str, deployment: &str, scene_xml: &str) -> Trace {
    let task = es_ir::serial::task_from_toml(task).expect("task");
    let obs = es_ir::serial::observation_from_toml(observation).expect("observation");
    let deploy = es_ir::serial::deployment_from_toml(deployment).expect("deployment");
    let scene = es_assets::parse_mjcf(scene_xml).expect("scene").scene;

    let mut domains = BatchDomains::single_env_at(
        TickRate::from_period_secs(scene.options.timestep).expect("physics rate"),
        deploy.rate.control,
    )
    .expect("domains");
    for d in [
        &mut domains.simulation,
        &mut domains.observation,
        &mut domains.inference,
    ] {
        d.batch = N_ENVS;
    }
    let mut env: Env<MuJoCoCpuBackend> =
        Env::new(&task, &scene, MuJoCoCpuBackend::new(), &domains, SEED).expect("env");
    let n_envs = N_ENVS as usize;
    let mut plans: Vec<CpuPlan> = (0..n_envs)
        .map(|_| CpuPlan::compile(&obs, PlanMode::Release).expect("plan"))
        .collect();
    let sources = input_sources(&plans[0], &obs, &task, Some(env.model())).expect("sources");
    let mut planes: Vec<SafetyPlane<NJ, H>> = (0..n_envs)
        .map(|_| SafetyPlane::from_ir(&deploy).expect("plane"))
        .collect();

    let light = LightOverride::default();
    let mut ctrl = vec![0.0; n_envs * NJ];
    let mut steps = Vec::new();
    for step in 0..STEPS {
        if step == RESET_AT {
            env.reset(Some(&[0])).expect("reset");
            planes[0].begin_episode();
            plans[0].reset();
        }
        let mut qpos = Vec::new();
        let mut observations: BTreeMap<String, Vec<f64>> = BTreeMap::new();
        {
            let model = env.model();
            let state = env.backend().state();
            for (i, plan) in plans.iter_mut().enumerate() {
                let view = env_view(&state, i);
                qpos.extend_from_slice(view.qpos);
                let (names, bytes, _) =
                    capture(plan, &sources, model, &view, None, &light, None).expect("capture");
                let inputs: BTreeMap<String, TensorRef<'_>> = names
                    .iter()
                    .zip(&bytes)
                    .map(|((name, dtype, shape), data)| {
                        (
                            name.clone(),
                            TensorRef::new(*dtype, shape.clone(), data.as_slice()),
                        )
                    })
                    .collect();
                for (name, tensor) in &plan.run(&inputs).expect("plan run") {
                    observations
                        .entry(name.clone())
                        .or_default()
                        .extend(f32s(tensor));
                }
            }
        }
        let sampled = actions(step, n_envs);
        let now = PhysTick(step);
        let mut events = Vec::new();
        {
            let state = env.backend().state();
            for (i, plane) in planes.iter_mut().enumerate() {
                let view = env_view(&state, i);
                let (q, qd) = joint_state::<NJ>(&view);
                plane.observe_state(&q, &qd);
                plane.heartbeat(now);
                let mut rows = [[0.0; NJ]; H];
                rows[0].copy_from_slice(&sampled[i * NJ..(i + 1) * NJ]);
                let chunk =
                    ActionChunk::new(rows, 1, deploy.execution).with_seq(step.saturating_add(1));
                let safe = plane.validate(&chunk, Micros(0), now);
                ctrl[i * NJ..(i + 1) * NJ].copy_from_slice(&safe.q);
                events.push(safe.events.bits());
            }
        }
        let out = env.step(&ctrl).expect("step");
        for (i, done) in out.dones.iter().enumerate() {
            if *done {
                planes[i].begin_episode();
                plans[i].reset();
            }
        }
        steps.push(StepRec {
            qpos,
            observations,
            executed: ctrl.clone(),
            events,
            rewards: out.rewards,
            dones: out.dones,
        });
    }
    Trace {
        schema: 1,
        n_envs: N_ENVS,
        seed: SEED,
        steps,
    }
}

/// The same run through the binding.
fn through_rollout(task: &str, observation: &str, deployment: &str, scene_xml: &str) -> Trace {
    let mut roll =
        Rollout::<NJ, H>::new(task, observation, deployment, scene_xml, SEED, N_ENVS).expect("new");
    let n_envs = N_ENVS as usize;
    let mut steps = Vec::new();
    for step in 0..STEPS {
        if step == RESET_AT {
            roll.reset(Some(&[0])).expect("reset");
        }
        assert_eq!(roll.tick(), step, "the rollout counts control ticks");
        let qpos: Vec<f64> = (0..n_envs).flat_map(|i| roll.qpos(i)).collect();
        let observations = roll.observe().expect("observe");
        let act = roll.act(&actions(step, n_envs)).expect("act");
        steps.push(StepRec {
            qpos,
            observations,
            executed: act.executed,
            events: act.events,
            rewards: act.rewards,
            dones: act.dones,
        });
    }
    Trace {
        schema: 1,
        n_envs: N_ENVS,
        seed: SEED,
        steps,
    }
}

#[test]
#[ignore = "needs MuJoCo through ES_PYTHON (spec 1.4's reference backend)"]
fn rollout_matches_es_eval_loop() {
    if let Err(why) = MuJoCoCpuBackend::is_available() {
        println!("SKIP rollout_matches_es_eval_loop: {why}");
        return;
    }
    let (task, observation, deployment, scene) = documents();

    let mine = through_rollout(&task, &observation, &deployment, &scene);
    let theirs = hand_rolled(&task, &observation, &deployment, &scene);
    // Compared as text: `serde_json` writes the shortest decimal that round-trips, so equal
    // text is equal bits, and a mismatch names the step it happened on.
    let mine_json = serde_json::to_string_pretty(&mine).expect("serialize");
    let theirs_json = serde_json::to_string_pretty(&theirs).expect("serialize");
    for (step, (a, b)) in mine.steps.iter().zip(&theirs.steps).enumerate() {
        assert_eq!(a, b, "step {step} differs from the hand-rolled loop");
    }
    assert_eq!(mine_json, theirs_json);

    let golden = repo_root().join("tests/golden/rollout/so101_100steps.json");
    if std::env::var("ES_GENERATE_GOLDENS").as_deref() == Ok("1") {
        std::fs::create_dir_all(golden.parent().expect("has a parent")).expect("mkdir");
        std::fs::write(&golden, format!("{mine_json}\n")).expect("write the golden");
        println!("wrote {}", golden.display());
        return;
    }
    let committed =
        std::fs::read_to_string(&golden).unwrap_or_else(|e| panic!("{}: {e}", golden.display()));
    assert_eq!(
        committed.replace("\r\n", "\n").trim_end(),
        mine_json,
        "the rollout no longer reproduces {}",
        golden.display()
    );
    println!("RAN rollout_matches_es_eval_loop: {STEPS} steps x {N_ENVS} envs match the golden");
}
