//! The Run tab's words about a finished run (spec 23.3, spec 10.5; packet M7/E1).
//!
//! Reading the run — `report.json`, `events.json`, `traj/`, `frames/` — is
//! [`es_eval::run_dir`]'s, next to the code that writes those files (packet M12/Y4). What stays
//! here is what a person reads: the strip's heading, the per-kind line, the table's column
//! keys and the status line. Which clock a person is shown is a decision, so it is made here
//! with a test rather than in `app.rs` (spec 28.10 rule 3).

use es_eval::run_dir::{KindRow, RunDir, Timeline};

/// The strip's own heading: `"nominal-00: 224 frame(s)"`. Frames, not ticks — the rows are
/// `events.json` records, one per control step, and [`kind_label`] counts the same thing.
pub fn timeline_heading(timeline: &Timeline, cell: &str) -> String {
    format!("{cell}: {} frame(s)", timeline.rows.len())
}

/// One line of the per-kind summary: both clocks, the strip's one first, so "first at frame
/// 136" can be found by eye on the strip above it.
pub fn kind_label(row: &KindRow) -> String {
    format!(
        "{:?}: {} frame(s), first at frame {} (tick {})",
        row.kind, row.frames, row.first.frame, row.first.tick
    )
}

/// Table headers in order: the three identity columns, then one per metric the report
/// carries — the column indices [`RunDir::sort_by`] takes.
pub fn columns(run: &RunDir) -> Vec<String> {
    let mut out = vec!["cell".to_owned(), "suite".to_owned(), "seed".to_owned()];
    out.extend(run.metric_names());
    out
}

/// The status line for an opened run: how many cells, and what the directory did not hold.
pub fn status(run: &RunDir) -> String {
    let n = run.cells().len();
    if run.missing.is_empty() {
        format!("{n} cell(s), complete")
    } else {
        format!("{n} cell(s); no {}", run.missing.join(", no "))
    }
}

#[cfg(test)]
mod tests {
    use std::path::{Path, PathBuf};

    use es_safety::ViolationKind;

    use super::*;

    /// The committed fixture run, generated by `es_eval::run_dir`'s `generate_fixture_run`.
    fn fixture() -> PathBuf {
        Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../.."))
            .join("tests/fixtures/visible-learning/run")
    }

    /// The per-kind summary labels both clocks, the strip's frame index first: a run records
    /// several physics ticks per control frame, and only the frame is a place on the strip.
    #[test]
    fn a_kind_row_labels_the_frame_and_the_tick() {
        let view = RunDir::open(&fixture()).expect("open the fixture run");
        let timeline = view.timeline("nominal-01");
        assert_eq!(
            timeline_heading(&timeline, "nominal-01"),
            "nominal-01: 4 frame(s)"
        );
        let rows = timeline.kind_rows();
        assert_eq!(rows.len(), 2, "{rows:?}");
        let velocity = rows
            .iter()
            .find(|r| r.kind == ViolationKind::Velocity)
            .expect("the fixture clamps velocity");
        assert_eq!((velocity.frames, velocity.first.frame), (2, 1));
        assert_eq!(
            kind_label(velocity),
            "Velocity: 2 frame(s), first at frame 1 (tick 1)"
        );
        assert!(view.timeline("nominal-00").kind_rows().is_empty());
    }

    /// The status line names every file a partial run is missing, and a whole one as whole.
    #[test]
    fn the_status_line_names_what_is_missing() {
        let view = RunDir::open(&fixture()).expect("open the fixture run");
        assert_eq!(status(&view), "4 cell(s), complete");
        assert!(columns(&view).len() >= 4, "{:?}", columns(&view));

        let dir = std::env::temp_dir().join(format!("es-editor-status-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("scratch dir");
        std::fs::copy(fixture().join("report.json"), dir.join("report.json")).expect("copy report");
        let alone = RunDir::open(&dir).expect("a report alone opens");
        assert_eq!(
            status(&alone),
            "2 cell(s); no events.json, no traj/, no frames/"
        );
        std::fs::remove_dir_all(&dir).ok();
    }
}
